export const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f9fafb",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  header: {
    backgroundColor: "#ffffff",
    borderBottom: "2px solid #2563eb",
    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
  },
  headerContent: {
    maxWidth: "72rem",
    margin: "0 auto",
    padding: "1rem 1.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logoContainer: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "3rem",
    height: "3rem",
    backgroundColor: "#2563eb",
    borderRadius: "0.25rem",
  },
  title: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#111827",
    margin: 0,
  },
  subtitle: {
    fontSize: "0.875rem",
    color: "#4b5563",
    fontWeight: "500",
    margin: 0,
  },
  mainContent: {
    maxWidth: "72rem",
    margin: "0 auto",
    padding: "2rem 1.5rem",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: "0.5rem",
    boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
    border: "none",
    marginBottom: "1.5rem",
  },
  cardContent: {
    padding: "2rem",
  },
  button: {
    backgroundColor: "#2563eb",
    color: "#ffffff",
    border: "none",
    borderRadius: "0.375rem",
    padding: "0.5rem 1.5rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  buttonSecondary: {
    backgroundColor: "transparent",
    color: "#374151",
    border: "1px solid #d1d5db",
    borderRadius: "0.375rem",
    padding: "0.5rem 1.5rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    backgroundColor: "#ffffff",
    borderRadius: "0.5rem",
    overflow: "hidden",
  },
  tableHeader: {
    backgroundColor: "#2563eb",
    color: "#ffffff",
  },
  tableHeaderCell: {
    padding: "0.75rem 1rem",
    textAlign: "left" as const,
    fontWeight: "600",
    fontSize: "0.875rem",
  },
  tableCell: {
    padding: "0.75rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.875rem",
  },
  tableRow: {
    backgroundColor: "#ffffff",
  },
  sectionTitle: {
    fontSize: "1.125rem",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "1rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  badge: {
    backgroundColor: "#2563eb",
    color: "#ffffff",
    padding: "0.25rem 1rem",
    borderRadius: "0.25rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    display: "inline-block",
  },
  reportHeader: {
    textAlign: "center" as const,
    marginBottom: "2rem",
    paddingBottom: "1.5rem",
    borderBottom: "2px solid #2563eb",
  },
  reportTitle: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "0.5rem",
    margin: "0 0 0.5rem 0",
  },
};
